dist: trusty
sudo: false
language: node_js
node_js:
- '9'
os:
- linux
cache: yarn
env:
- FIREFOX_VERSION="latest"
- FIREFOX_VERSION="59.0.2"
before_install:
- echo $FIREFOX_VERSION
- export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
- wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
- mkdir /tmp/firefox-$FIREFOX_VERSION
- tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
- export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=/usr/bin/google-chrome
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation google-chrome-stable
install:
- yarn install
script:
- firefox --version
- npm run lint
- npm run test:once
- npm run e2e
- npm run packagr
deploy:
  provider: npm
  email: gunther.bachmann@itemis.de
  api_key:
    secure: ML215iklUZUYYo6v+n0FAgvbDgkuwoDMTVqT4/DTegmFgGttq6oUuJONZUygibnh0fcsnv5kS/fWTqbxh4iFVHqzarOAaF1judY4tJs/f+8kZHu6OQVAM+GYyMqHu5OLD1F0XdwyI6EDjgvpHcDIL35S59GHrZngNn6VCKfo/W0Uz7TjcOqfyJEYHd/ny2BHddULIdd9ZuhVFApdEIyeo3HUSOUCegWZIPWRSTdY9Yt2OS4YAy+x9Mj3k9VBY9bIuRBQV+w22beQKHWR3DHa+D9oVdDOncn4tvcdYiOZQrLB8SleCbi1HmB3pX4FXrAw+Fm5bmLmtsKR25FU12kVeFRQWny3IpIZvSauIDLLdtcbdX8tGsfBQYATDoSn9PXNPQFPF/fJG9vmrwZIZnvCykET2h/9iuMdICnDEBEzqTpTNK17sOkOHlqv2CCl3yoCSisazfPsC76On4Ub0rOZNZ6JiWCNJEk+iSEhSGxl0SzDA7XI/amex8YD2m4xFBHyhsYpn+9wu38j08aYHBOouyYwy4Tb6TJih2stSMqj1WiOSITMKsIZgEGiP1qfm02/ckeZerPDQOY8ydALcVDVjcJRe01Tdz2QpIg/UGbKwxWiY3SMKmIsEp3l2Bh3F1gE8khBoB/q1sK2brvhkNpz2r5/uQQbG/axH93H5jAw/34=
  on:
    tags: true
    repo: test-editor/web-testexec-navigator
